import {requireFrame} from 'app/utils/packedImages';
import {getSolidTintedImage} from 'app/utils/tintedImages';

const spaceWidth = 4;
const arFont = {
    // This image is generated by calling generateFontImage('Habbo', 16), saving the resulting image and character widths
    // then editing the image to change the font to white pixels with no anti-aliasing.
    fontSource: 'gfx/hud/arFont.png',
    characters: '1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ/.*+!?$-()',
    height: 5,
    widths: [
        // 1-9,0
        4,4,4,4,4,4,4,4,4,4,
        // A-G
        5,5,4,5,4,4,5,
        // H-P
        4,4,5,5,4,6,5,5,5,
        // Q-Z
        6,5,4,4,5,6,6,5,4,4,
        // '/'.*+!?$-()
        4, 2, 4, 4, 2, 6, 5, 4, 3, 3
    ],
    frameMap: {} as {[key: string]: Frame},
    scale: 1,
};
const smallWhiteFont = {
    ...arFont,
    frameMap: {} as {[key: string]: Frame},
};

requireFrame(arFont.fontSource, {x: 0, y: 0, w: 282, h: 5}, frame => {
    const smallWhiteFontFrame = getSolidTintedImage('#FFF', frame);
    let x = 0;
    for (let i = 0; i < smallWhiteFont.characters.length; i++) {
        const w = smallWhiteFont.widths[i];
        smallWhiteFont.frameMap[smallWhiteFont.characters[i]] = {
            ...smallWhiteFontFrame, x, w, h: smallWhiteFont.height, s: smallWhiteFont.scale
        };
        x += w;
    }
});

let x = 0;
for (let i = 0; i < arFont.characters.length; i++) {
    const w = arFont.widths[i];
    arFont.frameMap[arFont.characters[i]] = requireFrame(arFont.fontSource, {x, y: 0, w, h: arFont.height, s: arFont.scale});
    x += w;
}

interface TextOptions {
    textAlign: 'left' | 'center' | 'right'
    textBaseline: 'top' | 'middle' | 'bottom'
}

export function drawARFont(context: CanvasRenderingContext2D, text: string|number, x: number, y: number,
    textOptions: Partial<TextOptions>
) {
    return drawSmallFont(context, arFont, text, x, y, textOptions);
}

export function drawSmallWhiteFont(context: CanvasRenderingContext2D, text: string|number, x: number, y: number,
    textOptions: Partial<TextOptions>
) {
    return drawSmallFont(context, smallWhiteFont, text, x, y, textOptions);
}


export function drawSmallFont(context: CanvasRenderingContext2D, font: typeof arFont, text: string|number, x: number, y: number,
    {textAlign = 'left', textBaseline = 'bottom'}: Partial<TextOptions>
) {
    text = `${text}`;
    x = x | 0;
    y = y | 0;

    let textWidth = 0;
    for (let c of text) {
        const frame = font.frameMap[c] || font.frameMap[c.toUpperCase()];
        if (frame) {
            textWidth += frame.w;
        } else {
            textWidth += spaceWidth;
        }
    }

    if (textBaseline === 'middle') y = Math.round(y - font.height / 2);
    else if (textBaseline === 'bottom') y = Math.round(y -  font.height);

    if (textAlign === 'center') x = Math.round(x - textWidth / 2);
    else if (textAlign === 'right') x = Math.round(x - textWidth);

    for (const c of text) {
        const frame = font.frameMap[c] || font.frameMap[c.toUpperCase()];
        if (frame) {
            context.drawImage(frame.image,
                frame.x, frame.y, frame.w, frame.h,
                x, y, frame.w, frame.h,
            );
            x += frame.w;
        } else {
            x += spaceWidth;
        }
    }
    return textWidth;
}
